# Generated by Django 4.0.3 on 2022-03-14 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moringaschool', '0005_course_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='moringaschool.cohort')),
            ],
        ),
    ]
