# Generated by Django 4.0.3 on 2022-03-14 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moringaschool', '0005_course_student'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cohort',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='moringaschool.cohort'),
        ),
    ]
