# Generated by Django 4.0.3 on 2022-03-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moringaschool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='module',
            new_name='cohort',
        ),
    ]
