# Generated by Django 4.0.3 on 2022-03-11 19:18

from django.db import migrations
import moringaschool.fields


class Migration(migrations.Migration):

    dependencies = [
        ('moringaschool', '0003_video_text_image_file_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=moringaschool.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=moringaschool.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
