# Generated by Django 4.0.3 on 2022-03-29 16:35

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('moringaschool', '0005_course_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=100, size=[400, 300], upload_to='images'),
        ),
    ]
